#!/usr/bin/env python3
"""
Excel2Insights Pro — Interactive Dashboard Generator

Generates a polished self-contained HTML dashboard from data analysis results
and interactive Plotly charts. Supports brand customization and PDF export.

Usage:
    python3 scripts/dashboard-generator.py \\
        --analysis output/analysis.json \\
        --charts output/charts/ \\
        --output output/dashboard.html \\
        --brand-json brand-config.json
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

try:
    import pandas as pd
except ImportError:
    pd = None


DEFAULT_BRAND = {
    "company_name": "Data Insights",
    "logo_url": "",
    "primary_color": "#1a73e8",
    "secondary_color": "#34a853",
    "accent_color": "#ea4335",
    "font_family": "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    "show_footer": True,
    "footer_text": "Generated by Excel2Insights Pro"
}


DASHBOARD_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} — Data Dashboard</title>
<style>
  :root {{
    --primary: {primary_color};
    --secondary: {secondary_color};
    --accent: {accent_color};
    --bg: #f8f9fa;
    --card-bg: #ffffff;
    --text: #202124;
    --text-muted: #5f6368;
    --border: #e0e0e0;
    --font: {font_family};
  }}
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:var(--font); background:var(--bg); color:var(--text); line-height:1.6; }}
  .header {{ background:linear-gradient(135deg,var(--primary),var(--secondary)); color:#fff; padding:48px 24px; text-align:center; }}
  .header h1 {{ font-size:2em; margin-bottom:8px; }}
  .header .subtitle {{ opacity:.85; font-size:1.1em; }}
  .header .meta {{ margin-top:16px; font-size:.85em; opacity:.7; }}
  .container {{ max-width:1200px; margin:0 auto; padding:24px; }}
  .section {{ margin-bottom:32px; }}
  .section-title {{ font-size:1.3em; font-weight:600; margin-bottom:16px; padding-bottom:8px; border-bottom:2px solid var(--primary); }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(280px,1fr)); gap:16px; }}
  .card {{ background:var(--card-bg); border-radius:8px; padding:20px; box-shadow:0 1px 3px rgba(0,0,0,.08); }}
  .card h3 {{ color:var(--primary); margin-bottom:8px; font-size:1em; }}
  .card .value {{ font-size:1.8em; font-weight:700; }}
  .card .label {{ color:var(--text-muted); font-size:.85em; }}
  .card table {{ width:100%; border-collapse:collapse; font-size:.9em; }}
  .card td {{ padding:4px 8px; border-bottom:1px solid var(--border); }}
  .card td:first-child {{ font-weight:500; }}
  .chart-grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(500px,1fr)); gap:20px; }}
  .chart-card {{ background:var(--card-bg); border-radius:8px; overflow:hidden; box-shadow:0 1px 3px rgba(0,0,0,.08); }}
  .chart-card h3 {{ padding:12px 16px; background:var(--primary); color:#fff; font-size:.95em; }}
  .chart-card iframe {{ width:100%; height:420px; border:none; display:block; }}
  .insights-list {{ list-style:none; }}
  .insights-list li {{ padding:10px 16px; margin-bottom:8px; background:var(--card-bg); border-radius:6px; border-left:3px solid var(--primary); }}
  .insights-list .tag {{ display:inline-block; padding:2px 8px; border-radius:4px; font-size:.8em; font-weight:600; }}
  .tag-green {{ background:#e6f4ea; color:#137333; }}
  .tag-yellow {{ background:#fef7e0; color:#b06000; }}
  .tag-red {{ background:#fce8e6; color:#c5221f; }}
  .footer {{ text-align:center; padding:24px; color:var(--text-muted); font-size:.85em; border-top:1px solid var(--border); margin-top:48px; }}
  @media (max-width:600px) {{
    .chart-grid {{ grid-template-columns:1fr; }}
    .grid {{ grid-template-columns:1fr; }}
    .header {{ padding:32px 16px; }}
    .header h1 {{ font-size:1.5em; }}
  }}
</style>
</head>
<body>

<div class="header">
  {logo_html}
  <h1>{title}</h1>
  <div class="subtitle">{subtitle}</div>
  <div class="meta">Generated {date} · {row_count} rows · {col_count} columns</div>
</div>

<div class="container">

<!-- Summary Cards -->
<div class="section">
  <div class="section-title">📊 Overview</div>
  <div class="grid">
    {summary_cards}
  </div>
</div>

<!-- Data Quality -->
<div class="section">
  <div class="section-title">🔍 Data Quality</div>
  <div class="grid">
    <div class="card"><h3>Missing Values</h3><table>{missing_table}</table></div>
    <div class="card"><h3>Column Profile</h3><table>{column_table}</table></div>
  </div>
</div>

<!-- Charts -->
<div class="section">
  <div class="section-title">📈 Interactive Charts</div>
  <div class="chart-grid">
    {chart_embeds}
  </div>
</div>

<!-- Key Insights -->
<div class="section">
  <div class="section-title">💡 Key Insights</div>
  <ul class="insights-list">
    {insights}
  </ul>
</div>

</div>

{footer_html}

</body>
</html>"""


def load_brand_config(path):
    """Load brand configuration from JSON file."""
    if path and os.path.exists(path):
        try:
            with open(path) as f:
                user_config = json.load(f)
            config = DEFAULT_BRAND.copy()
            config.update(user_config)
            return config
        except Exception as e:
            print(f"⚠️  Brand config error: {e}, using defaults")
    return DEFAULT_BRAND.copy()


def load_analysis(analysis_path):
    """Load analysis results JSON."""
    if analysis_path and os.path.exists(analysis_path):
        with open(analysis_path) as f:
            return json.load(f)
    return {}


def read_chart_html(chart_path):
    """Read an interactive chart HTML file."""
    if os.path.exists(chart_path):
        with open(chart_path) as f:
            return f.read()
    return "<p style='color:#999'>Chart not available</p>"


def build_summary_cards(analysis, df, brand):
    """Build summary stat cards."""
    num_cols = analysis.get("numeric_columns", [])
    cat_cols = analysis.get("categorical_columns", [])
    total_rows = len(df) if df is not None else 0
    total_cols = len(df.columns) if df is not None else 0

    cards = ""
    pairs = [
        ("📋 Total Rows", f"{total_rows:,}", "Data records"),
        ("📋 Total Columns", str(total_cols), "Features"),
        ("🔢 Numeric", str(len(num_cols)), "Numeric columns"),
        ("🏷️ Categorical", str(len(cat_cols)), "Category columns"),
    ]
    missing = analysis.get("missing_values", {}).get("total_missing", 0)
    missing_pct = round(missing / max(total_rows * total_cols, 1) * 100, 1) if total_rows and total_cols else 0
    pairs.append(("⚠️ Missing", f"{missing:,} ({missing_pct}%)", "Data completeness"))

    for label, value, desc in pairs:
        cards += f'<div class="card"><h3>{label}</h3><div class="value">{value}</div><div class="label">{desc}</div></div>\n'

    return cards


def build_missing_table(analysis):
    """Build missing values table."""
    missing = analysis.get("missing_values", {})
    if not missing:
        return "<tr><td>No missing data</td></tr>"

    cols = missing.get("columns", {})
    if isinstance(cols, dict):
        rows = ""
        for col, count in sorted(cols.items(), key=lambda x: -x[1])[:10]:
            pct = round(count / max(analysis.get("total_rows", 1), 1) * 100, 1)
            rows += f"<tr><td>{col}</td><td>{count}</td><td>{pct}%</td></tr>\n"
        return rows
    return "<tr><td>N/A</td></tr>"


def build_column_table(analysis):
    """Build column profile table."""
    cols = analysis.get("column_types", {})
    if isinstance(cols, dict):
        rows = ""
        for col, dtype in list(cols.items())[:15]:
            rows += f"<tr><td>{col}</td><td style='color:var(--text-muted)'>{dtype}</td></tr>\n"
        return rows
    return "<tr><td>N/A</td></tr>"


def build_chart_embeds(chart_files):
    """Embed chart HTML files."""
    embeds = ""
    for chart_type, files in chart_files.items():
        for f in files:
            html = read_chart_html(f)
            title = os.path.basename(f).replace(".html", "").replace("_", " ").title()
            embeds += f'<div class="chart-card"><h3>{title}</h3><div style="padding:4px">{html}</div></div>\n'
    return embeds or "<p style='color:#999'>No charts generated</p>"


def build_insights(analysis):
    """Build key insights list."""
    items = analysis.get("insights", [])
    if not items:
        items = [
            "Analysis completed — review the charts and data quality section for key findings.",
            "Data quality check: review missing values and duplicates.",
            "Explore interactive charts by hovering and zooming."
        ]
    html = ""
    for item in items[:10]:
        tag = "info"
        if isinstance(item, dict):
            tag = item.get("tag", "info")
            text = item.get("text", str(item))
        else:
            text = item
        color_class = {"positive": "tag-green", "warning": "tag-yellow", "error": "tag-red"}.get(tag, "tag-green")
        html += f'<li><span class="tag {color_class}">{tag}</span> {text}</li>\n'
    return html


def generate_dashboard(analysis, chart_files, output_path, brand_config, df=None):
    """Generate the complete HTML dashboard."""
    brand = brand_config
    logo_html = f'<img src="{brand["logo_url"]}" style="height:48px;margin-bottom:16px">' if brand.get("logo_url") else ""

    title = os.path.basename(analysis.get("file", "Dataset")).replace("_", " ").replace(".csv", "").replace(".xlsx", "").title() if analysis.get("file") else "Data Dashboard"

    summary_cards = build_summary_cards(analysis, df, brand)
    missing_table = build_missing_table(analysis)
    column_table = build_column_table(analysis)
    chart_embeds = build_chart_embeds(chart_files)
    insights = build_insights(analysis)
    footer_html = f'<div class="footer">{brand["footer_text"]}</div>' if brand.get("show_footer") else ""

    html = DASHBOARD_TEMPLATE.format(
        title=title,
        subtitle="Comprehensive Data Analysis Dashboard",
        date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        row_count=analysis.get("total_rows", "N/A"),
        col_count=analysis.get("total_columns", "N/A"),
        primary_color=brand["primary_color"],
        secondary_color=brand["secondary_color"],
        accent_color=brand["accent_color"],
        font_family=brand["font_family"],
        logo_html=logo_html,
        summary_cards=summary_cards,
        missing_table=missing_table,
        column_table=column_table,
        chart_embeds=chart_embeds,
        insights=insights,
        footer_html=footer_html,
    )

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(html)
    return output_path


def build_brand_template(output_path):
    """Generate a sample brand configuration JSON template."""
    template = DEFAULT_BRAND.copy()
    template["company_name"] = "Your Company"
    template["primary_color"] = "#1a73e8"
    template["secondary_color"] = "#34a853"
    template["accent_color"] = "#ea4335"
    template["show_footer"] = True
    template["footer_text"] = "Generated by Excel2Insights Pro | Your Company"

    with open(output_path, "w") as f:
        json.dump(template, f, indent=2, ensure_ascii=False)
    print(f"✅ Brand template saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Excel2Insights Pro — Interactive Dashboard Generator")
    parser.add_argument("--file", help="Path to original data file (for stats)")
    parser.add_argument("--analysis", required=True, help="Path to analysis JSON")
    parser.add_argument("--charts", default="output/charts", help="Chart directory")
    parser.add_argument("--output", default="output/dashboard.html", help="Output dashboard path")
    parser.add_argument("--brand-json", help="Brand configuration JSON")
    parser.add_argument("--init-brand", help="Generate brand template JSON at this path", metavar="PATH")
    parser.add_argument("--json", action="store_true", help="Output results as JSON")
    args = parser.parse_args()

    if args.init_brand:
        build_brand_template(args.init_brand)
        return

    analysis = load_analysis(args.analysis)

    df = None
    if args.file and os.path.exists(args.file):
        try:
            from chart_generator import load_data
            df = load_data(args.file)
            if df is not None:
                analysis["total_rows"] = len(df)
                analysis["total_columns"] = len(df.columns)
        except Exception:
            pass

    # Collect chart files from directory
    chart_files = {"charts": []}
    if os.path.exists(args.charts):
        for f in sorted(os.listdir(args.charts)):
            if f.endswith(".html"):
                chart_files["charts"].append(os.path.join(args.charts, f))

    brand = load_brand_config(args.brand_json)
    output_path = generate_dashboard(analysis, chart_files, args.output, brand, df)

    file_size = os.path.getsize(output_path)
    print(f"✅ Dashboard generated: {output_path}")
    print(f"   Size: {file_size:,} bytes")
    print(f"   Charts embedded: {len(chart_files['charts'])}")

    if args.json:
        print(json.dumps({"path": output_path, "size": file_size, "charts": len(chart_files["charts"])}))


if __name__ == "__main__":
    main()
