#!/usr/bin/env python3
"""
Excel2Insights — Report Generator
Generate structured Markdown/HTML insight reports from analysis results and charts.
"""

import argparse
import json
import sys
from pathlib import Path
from datetime import datetime

try:
    import pandas as pd
except ImportError:
    HAS_PANDAS = False
else:
    HAS_PANDAS = True


def load_analysis_data(filepath, sheet=None, encoding="utf-8", chart_dir=None):
    """Load data and run analysis inline, or read pre-computed analysis."""
    if not HAS_PANDAS:
        return {"error": "pandas not available"}
    ext = Path(filepath).suffix.lower()
    if ext in (".xlsx", ".xls"):
        if sheet:
            df = pd.read_excel(filepath, sheet_name=sheet)
        else:
            xls = pd.ExcelFile(filepath)
            df = pd.read_excel(filepath, sheet_name=xls.sheet_names[0])
    elif ext == ".tsv":
        df = pd.read_csv(filepath, sep="\t", encoding=encoding)
    else:
        df = pd.read_csv(filepath, encoding=encoding)
    return df


def discover_charts(chart_dir):
    if not chart_dir or not Path(chart_dir).exists():
        return []
    chart_dir = Path(chart_dir)
    images = sorted(chart_dir.glob("*.png"))
    return [str(p) for p in images]


def generate_html_report(df, charts, output_path):
    """Generate a standalone HTML report with embedded charts."""
    n_rows, n_cols = df.shape
    num_cols = df.select_dtypes(include="number").columns.tolist() if HAS_PANDAS else []
    cat_cols = df.select_dtypes(include="object").columns.tolist() if HAS_PANDAS else []
    missing_total = int(df.isnull().sum().sum()) if HAS_PANDAS else 0
    duplicates = int(df.duplicated().sum()) if HAS_PANDAS else 0

    # Quick stats
    stats_html = ""
    if num_cols:
        stats = df[num_cols].describe().round(2)
        stats_html = stats.to_html(classes="data-table")

    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head><meta charset="UTF-8">
<title>Data Insight Report</title>
<style>
body {{ font-family: -apple-system, 'PingFang SC', sans-serif; max-width: 960px; margin: 0 auto; padding: 20px; color: #1e293b; background: #f8fafc; }}
h1 {{ color: #1e293b; border-bottom: 2px solid #2b6af6; padding-bottom: 8px; }}
h2 {{ color: #2b6af6; margin-top: 32px; }}
table {{ border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 13px; }}
th, td {{ border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }}
th {{ background: #f1f5f9; font-weight: 600; }}
.data-table th {{ background: #2b6af6; color: #fff; }}
.chart {{ max-width: 100%; margin: 16px 0; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }}
.summary {{ background: #eef2ff; border-radius: 8px; padding: 16px; margin: 12px 0; }}
.summary span {{ font-weight: 600; color: #2b6af6; }}
.warn {{ background: #fff3d6; border-radius: 8px; padding: 12px 16px; margin: 8px 0; color: #925c00; }}
.footer {{ text-align: center; color: #94a3b8; font-size: 12px; margin-top: 40px; }}
</style>
</head>
<body>
<h1>Data Insight Report</h1>
<p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>

<div class="summary">
<h3>Dataset Overview</h3>
<p><span>{n_rows}</span> rows × <span>{n_cols}</span> columns</p>
<p>Numeric: {len(num_cols)} | Categorical: {len(cat_cols)} | Missing cells: {missing_total} | Duplicate rows: {duplicates}</p>
</div>

<h2>Column Summary</h2>
{stats_html if num_cols else '<p>No numeric columns for statistical summary.</p>'}

<h2>Visualizations</h2>
"""
    for chart_path in charts:
        rel = Path(chart_path).name
        html += f'<img class="chart" src="{chart_path}" alt="{rel}" />\n'

    if not charts:
        html += "<p>No charts generated.</p>"

    html += """
<h2>Column Types</h2>
<table>
<tr><th>Type</th><th>Count</th><th>Columns</th></tr>
"""
    if num_cols:
        html += f"<tr><td>Numeric</td><td>{len(num_cols)}</td><td>{', '.join(num_cols[:10])}{'...' if len(num_cols) > 10 else ''}</td></tr>"
    if cat_cols:
        html += f"<tr><td>Categorical</td><td>{len(cat_cols)}</td><td>{', '.join(cat_cols[:10])}{'...' if len(cat_cols) > 10 else ''}</td></tr>"

    if missing_total > 0:
        html += f'<div class="warn">⚠ Detected {missing_total} missing values and {duplicates} duplicate rows. Review data quality before downstream processing.</div>'

    html += '<div class="footer">Generated by Excel2Insights</div></body></html>'

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(html, encoding="utf-8")
    return output_path


def main():
    parser = argparse.ArgumentParser(description="Excel2Insights — Report Generator")
    parser.add_argument("--file", required=True, help="Path to data file")
    parser.add_argument("--sheet", help="Sheet name")
    parser.add_argument("--analysis", help="Pre-computed analysis JSON")
    parser.add_argument("--charts", help="Charts directory")
    parser.add_argument("--output", default="output/report.html", help="Output path")
    parser.add_argument("--format", default="html", choices=["html", "markdown", "pdf"])
    args = parser.parse_args()

    df = load_analysis_data(args.file, args.sheet)
    if isinstance(df, dict) and "error" in df:
        print(json.dumps(df))
        sys.exit(1)

    charts = discover_charts(args.charts)
    out = generate_html_report(df, charts, args.output)
    print(json.dumps({
        "report": out,
        "charts_embeded": len(charts),
        "format": args.format
    }, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
